Allow routes to check if user is student or instructor
rcos/venue pull request #410
Opened 2016-11-09 17:31 UTC by kmcnellis

works towards #400

2016-11-10 00:52 UTC, seveibar requested changes
:penguin: but honestly i think "has" and "is" are pretty low on the good variable name scale

2016-11-10 00:52 UTC, seveibar commented on client/components/auth/router.decorator.js
> +          .then(has => {
??? has?

2016-11-10 00:52 UTC, seveibar commented on client/components/auth/router.decorator.js
> +                $location.path(is ? '/' : '/login');
is? these variable names are not so great...

2016-11-10 03:54 UTC, kmcnellis commented on client/components/auth/router.decorator.js
> +                $location.path(is ? '/' : '/login');
Those were the names already used, I just duplicated them for consistency. Do you have a better name in mind?

2016-11-10 05:34 UTC, seveibar commented on client/components/auth/router.decorator.js
> +                $location.path(is ? '/' : '/login');
haha yea, `isLoggedIn` and `hasRole`, assuming thats what they actually mean (hasRole could be isStudent also?)

2016-11-12 20:55 UTC, kmcnellis commented
Fixed

2016-11-14 19:28 UTC, kmcnellis commented
@seveibar

2016-11-15 05:55 UTC, seveibar approved these changes

2016-11-15 05:56 UTC, merged