email preferences
rcos/venue pull request #418
Opened 2016-12-16 06:37 UTC by jowlee

Email preferences added to user setting page. 
API endpoint created for updating preferences

2016-12-18 07:57 UTC, kmcnellis requested changes

2016-12-18 07:57 UTC, kmcnellis commented on client/app/account/settings/settings.html
> +            <input type="checkbox" class="form-check-input" ng-model="emailAhead.applied" ng-disabled="!emailPreferences.unsubscribe">
This is confusing. The user should not have to click unsubscribe to change the event reminders. Instead they should be able to select any of them and click update (remove the Unsubscribe from emails checkbox).  There should also be a "Unsubscribe from all" button that deselects all and submits.

2016-12-18 07:57 UTC, kmcnellis commented on client/app/account/settings/settings.html
> +            {{ emailAhead.time }} before the event
The text should have a click pointer to indicate that you can click on the text

2017-03-04 23:13 UTC, kmcnellis commented
Where are the changes?

2017-03-05 00:51 UTC, vkr96 commented
I made a button that would enable and disable the ability to change the notifications. I had an un subscribe from all button, but, I thought it made more sense just to un-check all the options and then save. I can re-add the unsubscribe button if this setup does not work.

2017-03-06 18:29 UTC, kmcnellis commented
I don't really like the change button. The combination with the save button makes it look like a huge chunk of purple. The caption should either be just "edit", and be a small non-colored button next to "Email Notification" header, or non colored and alone at the bottom. Once in edit mode, it should switch to cancel. The save button should only be present in the edit mode

2017-03-06 18:29 UTC, kmcnellis commented
![screen shot 2017-03-06 at 1 26 31 pm](https://cloud.githubusercontent.com/assets/5566205/23623686/ed886c08-0270-11e7-8887-06c66f702411.png)
![screen shot 2017-03-06 at 1 26 09 pm](https://cloud.githubusercontent.com/assets/5566205/23623685/ed85b63e-0270-11e7-8b87-7d9191fae6fc.png)

2017-03-06 19:02 UTC, vkr96 commented
Okay, will work on changing the look of this

2017-03-09 03:33 UTC, kmcnellis commented
Thanks!

2017-03-09 03:33 UTC, merged